
jobs:
- job: test
  strategy:
    matrix:
      Linux py39:
        IMAGE_NAME: 'ubuntu-latest'
        PYTHON_VERSION: '3.12'
  pool:
    vmImage: $(IMAGE_NAME)
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: $(PYTHON_VERSION)
    - bash: |
        sudo apt-get install libsndfile1
        pip install numpy scipy Cython
    - bash: pip install -e .[all]
    - bash: pip install pytest pytest-azurepipelines pytest-cov pytest-rerunfailures
    - bash: pytest
