name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}


    - name: Install linux dependencies
      run: |
        trap 'echo -e "$ $BASH_COMMAND"' DEBUG
        sudo apt-get update
        sudo apt-get install libsndfile1 sox

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy scipy Cython
        pip install flake8 pytest pytest-cov codecov pytest-rerunfailures
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install --editable .[all]

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax error or undefined names
        #flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        #flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest -v
        python -m coverage xml --include="pb_bss*"
    - name: Codecov
      run: |
        codecov
